on:
  schedule:
    # runs everyday at 00:00 UTC
    - cron:  "0 0 * * *"

  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/repo_sync.yml'

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/thanos-io/thanos"
          source_branch: "main"
          destination_branch: "main"
          sync_tags: "true"
          github_token: ${{ secrets.SYNC_SECRET }}
